[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$rdW69763lpJSau2915oT4g$O9ebBlHI5eS4mPl6zT4OFI3/Oe.mnd2DKNLVUY5N9rIvRSX4O4cK.w2nOUA9OWKTEqCDP95YN1PUIlB7Y6Haow

