services:
  db:
    image: postgres:16
    container_name: odoo-jobber_module
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5438:5432"
    volumes:
      - odoo-jobber_module-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    container_name: odoo-jobber_module-web
    depends_on:
      - db
    ports:
      - "8074:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-jobber_module-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    restart: unless-stopped

volumes:
  odoo-jobber_module-db-data:
  odoo-jobber_module-web-data: