[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons, /mnt/extra-addons/appointment-main/custom,
	/mnt/extra-addons/appointment-main/enterprise
admin_passwd = $pbkdf2-sha512$600000$Tek9hzDGeM85x3ivNYbQWg$icS7PgUcMyCmKLuOxJmKnK7e770XCZ5OVG7QtXoO5IElKn3xyTRch2OAzjRMzA1Rb.esti2y0SsyGcuSTLzi/A
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

